# 端口设置
server:
  port: 80
  servlet:
    context-path: /dev

# 是否输出debug信息
debug: false

#jasypt对敏感配置项进行加密用 ,为了安全起见，秘钥最好不在这里设置。由于@test中需要，所以这里暂不注释
jasypt:
  encryptor:
    password: Aesop #引入密钥

#-------------------------------------spring 配置-----------------------------------
spring:

  http:
    encoding:
      charset: UTF-8

  # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /**

  #thymelea模板配置
  thymeleaf:
    enabled: true
    servlet:
      content-type: text/html
    prefix: classpath:/templates/   # 访问templates下的html文件需要配置模板，映射
    suffix: .html
    mode: HTML
    encoding: UTF-8
    #热部署文件，页面不产生缓存，及时更新,不然没法看到实时页面
    cache: false
    #是否在呈现模板之前检查模板是否存在
    check-template: true
    #检查模板位置是否正确(默认值:true)
    check-template-location: true

  #  #不扫描thymelea模板文件
  #  freemarker:
  #    checkTemplateLocation: false

  #数据源配置
  datasource:
    #    # mysql 数据库连接参数
    #    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    #    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=GMT%2B8
    #
    #    # p6spy
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #    url: jdbc:p6spy:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=GMT%2B8
    #
    #    username: root
    #    password: 123456
    #
    #    # hikari 连接池
    #    # Hikari will use the above plus the following to setup connection pooling
    #    type: com.zaxxer.hikari.HikariDataSource
    #    hikari:
    #      # 自动提交
    #      auto-commit: true
    #      connection-test-query: SELECT 1
    #      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
    #      # 生产环境 connect-time 10 s
    #      connection-timeout: 9000
    #      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    #      idle-timeout: 600000
    #      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout 7200s 参数（# 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->  ） -->
    #      max-lifetime: 1800000
    #      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    #      maximum-pool-size: 15
    #      # 最小连接数
    #      minimum-idle: 10
    #      # 连接池名字
    #      pool-name: DemoHikariCP

    #主从模式，配置多数据源
    #配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
      datasource:
        master:
          username: ENC(g3dRIY8u0U1scFFZanhBUA==)
          password: ENC(RX02nQEoemJ3px6rwVp0Yw==)
          driver-class-name: ENC(XSuVp5avV5H/umvurK0VVlCXTaE2S4KX0Fsr54wRPt2ZMw9ildQ/Y7h14DyWUcfs)
          url: ENC(wyYRvv6XSYji9PjVThKW+crn7EeCbRAonblI3+bkrMLTGhJb+BGFf/mOV0e/AGnw+X+aq0sJ2b0Za4Ergw2IT0TfOoxkd6xGYj9m+qyK26s1voCou+NsRRldtsautegnyqd+xO0xMADARIGJascShkQlqy/a5rSw)
          # hikari 连接池
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            # 自动提交
            auto-commit: true
            connection-test-query: SELECT 1
            # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
            # 生产环境 connect-time 10 s
            connection-timeout: 9000
            # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
            idle-timeout: 600000
            # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout 7200s 参数（# 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->  ） -->
            max-lifetime: 1800000
            # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
            maximum-pool-size: 15
            # 最小连接数
            minimum-idle: 10
            # 连接池名字
            pool-name: DemoHikariCP

        slave_1:
          username: ENC(1ZeRHDBzSgxfT1Ndrc423Q==)
          password: ENC(XlUBlrwG/MiR00pSNKTIHg==)
          driver-class-name: ENC(wzUruNicJ17VbX/zmecC0pGA0ABQbnHSQ/TgR8YfocwoXh6+NkLX3K7JjkmW4064)
          url: ENC(40/TjHtVKouKlh1AgV3Bw/bLgMKmB8xLhqXi8JB1fZoD+Al2kTpLUueDiJetcM/iQ7m2enX5U4o0rEmMGR7gm7L1u0tpkeWLq3W67SmQrdY/1DX/tWu1bBIT8m1BFidkIpSrm6641WYpVoBntSTtX2lMNkUc/9XF)
        slave_2:
          username: ENC(In4bpkLGnX0lkfSSqrCa5w==)
          password: ENC(gp/zwjJBqlqX2ofXJDEQmg==)
          driver-class-name: ENC(yMmHscHZsCXTv9pF7nSs0tlxM/ykkXh3X1GdTCWeSURZz6VbH5AeuC6Z0wkekcnU)
          url: ENC(uY3hs3lVJk6QXH/2cNhxoabHgbuWeuaWBatPGtqvX1a791vZwmXfLgv5mLboTD1it3wgESzyq7HWUwy4UndBQxUxzzPcJhbbBQxdufiFAi6LIOafI7AS4fL7xrfYiANAAgnLsJtdSfMs6IMXc3t1PkUDAHKAqikG)

  #redis缓存配置
  redis:
    database: 0     # Redis 数据库索引（默认为0）
    host: 127.0.0.1 # Redis 服务器地址
#    password: hzero # Redis 密码 如果你的redis服务本身没有设置密码，而在这里填写了密码，会报错！
    port: 6379      # Redis 服务器连接端口
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 30000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
    timeout: 3000   # Redis 连接超时时间（毫秒）

  #使用了Spring Cache后，能指定spring.cache.type就手动指定一下，虽然它会自动去适配已有Cache的依赖，但先后顺序会对Redis使用有影响（JCache -> EhCache -> Redis -> Guava）
  cache:
    redis:
      ## Entry expiration in milliseconds. By default the entries never expire.
      time-to-live: 1d
      #写入redis时是否使用键前缀。
      use-key-prefix: true
#-------------------------------------mybatis-plus 配置-----------------------------------
mybatis-plus:
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.hzero.demo.springboot.springbootdemo.web.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用 使用了p6spy就可以注释掉了
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 配置的缓存的全局开关
    cache-enabled: true
    # 延时加载的开关
    lazy-loading-enabled: true
    # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multiple-result-sets-enabled: true
    use-generated-keys: true
    default-statement-timeout: 60
    default-fetch-size: 100



